export enum AirlineId {
  Aegean = "a3",
  AirCanada = "ac",
  AirNewZealand = "nz",
  Ana = "nh",
  Asiana = "oz",
  Avianca = "av",
  Copa = "cm",
  EvaAir = "br",
  SingaporeAirlines = "sq",
  TapPortugal = "tp",
  Thai = "tg",
  TurkishAirlines = "tk",
  United = "ua",
  AeroMexico = "am",
  Delta = "dl",
  AirFrance = "af",
  KLM = "kl",
  KoreanAir = "ke",
  Saudia = "sv",
  VirginAtlantic = "vs",
  AmericanAirlines = "aa",
  Alaska = "as",
  CathayPacific = "cx",
  Finnair = "ay",
  JapanAirlines = "jl",
  Qantas = "qf",
  Qatar = "qr",
  BritishAirways = "ba",
  Iberia = "ib",
  AerLingus = "ei",
  Emirates = "ek",
  Etihad = "ey",
  Frontier = "f9",
  HainanAirlines = "hu",
  Hawaiian = "ha",
  JetBlue = "b6",
  Latam = "la",
  Southwest = "wn",
  VirginAustralia = "va",

  AirChina = "ca",
  AirIndia = "ai",
  Austrian = "os",
  BrusselsAirlines = "sn",
  CroatiaAirlines = "ou",
  Egyptair = "ms",
  Ethiopian = "et",
  LOTPolish = "lo",
  Lufthansa = "lh",
  Sas = "sk",
  ShenzhenAirlines = "zh",
  SouthAfrican = "sa",
  Swiss = "lx",
  AerolineasArgentinas = "ar",
  AirEuropa = "ux",
  ChinaAirlines = "ci",
  ChinaEastern = "mu",
  CzechAirlines = "ok",
  GarudaIndonesia = "ga",
  ItaAirways = "az",
  KenyaAirways = "kq",
  MiddleEast = "me",
  Tarom = "ro",
  VietnamAirlines = "vn",
  XiamenAir = "mf",
  MalaysiaAirlines = "mh",
  RoyalAirMaroc = "at",
  RoyalJordanian = "rj",
  SriLankanAirlines = "ul",
  Condor = "de",
  ElAl = "ly",
  Gol = "g3",
  WestJet = "ws",
  Starlux = 'jx'
}

export enum Alliance {
  StarAlliance = "Star Alliance",
  Skyteam = "Skyteam",
  OneWorld = "One World",
  NonAlliance = "Non-Alliance",
}

export enum Bank {
  Chase = "Chase",
  AmericanExpress = "AmericanExpress",
  Citi = "Citi",
  CapitalOne = "CapitalOne",
  Bilt = "Bilt",
  WellsFargo = "WellsFargo",
}

export type Airline = {
  id: AirlineId;
  name: string;
  alliance: Alliance;
  alsoBookable: AirlineId[];
  transferrableFrom: (Bank | { bank: Bank; rate: string })[];
  flag?: string;
};
